## PostgreSQL Integration with Jupyter Notebook

In [3]:
%load_ext sql

In [4]:
from sqlalchemy import create_engine

In [5]:
# Format
#%sql dialect+driver://username:password@host:port/database
# Example format
%sql postgresql://postgres:rahel23@localhost/moodle

In [6]:
#Format
#engine = create_engine('dialect+driver://username:password@host:port/database')
#Example format
engine = create_engine('postgresql://postgres:rahel23@localhost/moodle')

In [7]:
engine

Engine(postgresql://postgres:***@localhost/moodle)

### The number of public tables

In [8]:
%%sql
select count(*)
from information_schema.tables
where table_schema = 'public';

 * postgresql://postgres:***@localhost/moodle
1 rows affected.

[(448,)]

In [8]:
%%sql
select * from information_schema.tables
where table_schema = 'public';

 * postgresql://postgres:***@localhost/moodle
448 rows affected.

[('moodle', 'public', 'mdl_analytics_indicator_calc', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_analytics_models', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_analytics_models_log', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_analytics_predict_samples', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_analytics_prediction_actions', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_analytics_predictions', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_analytics_train_samples', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_analytics_used_analysables', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_analytics_used_files', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_assign', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_assign_grades', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_assign_overrides', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_assign_plugin_config', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_assign_submission', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_assign_user_flags', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_assign_user_mapping', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_assignfeedback_comments', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_assignfeedback_editpdf_annot', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_assignfeedback_editpdf_cmnt', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_assignfeedback_editpdf_queue', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_assignfeedback_editpdf_quick', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_assignfeedback_file', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_assignment', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_assignment_submissions', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_assignment_upgrade', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_assignsubmission_file', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_assignsubmission_onlinetext', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_auth_oauth2_linked_login', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_backup_controllers', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_backup_courses', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_backup_logs', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_badge', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_badge_backpack', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_badge_competencies', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_badge_criteria', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_badge_criteria_met', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_badge_criteria_param', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_badge_endorsement', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_badge_external', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_badge_issued', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_badge_manual_award', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_badge_related', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_block', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_block_community', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_block_configurable_reports', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_block_instances', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_block_positions', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_block_recent_activity', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_block_recentlyaccesseditems', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_block_rss_client', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_blog_association', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_blog_external', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_book', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_book_chapters', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_cache_filters', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_cache_flags', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_capabilities', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_chat', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_chat_messages', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_chat_messages_current', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_chat_users', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_choice', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_choice_answers', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_choice_options', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_cohort', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_cohort_members', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_comments', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_competency', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_competency_coursecomp', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_competency_coursecompsetting', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_competency_evidence', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_competency_framework', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_competency_modulecomp', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_competency_plan', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_competency_plancomp', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_competency_relatedcomp', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_competency_template', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_competency_templatecohort', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_competency_templatecomp', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_competency_usercomp', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_competency_usercompcourse', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_competency_usercompplan', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_competency_userevidence', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_competency_userevidencecomp', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_config', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_config_log', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_config_plugins', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_context', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_context_temp', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_course', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_course_categories', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_course_completion_aggr_methd', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_course_completion_crit_compl', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_course_completion_criteria', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_course_completion_defaults', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_course_completions', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_course_format_options', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_course_modules', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_course_modules_completion', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_course_published', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_course_request', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_course_sections', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_data', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_data_content', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_data_fields', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_data_records', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_editor_atto_autosave', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_enrol', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_enrol_flatfile', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_enrol_lti_lti2_consumer', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_enrol_lti_lti2_context', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_enrol_lti_lti2_nonce', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_enrol_lti_lti2_resource_link', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_enrol_lti_lti2_share_key', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_enrol_lti_lti2_tool_proxy', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_enrol_lti_lti2_user_result', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_enrol_lti_tool_consumer_map', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_enrol_lti_tools', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_enrol_lti_users', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_enrol_paypal', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_event', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_event_subscriptions', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_events_handlers', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_events_queue', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_events_queue_handlers', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_external_functions', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_external_services', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_external_services_functions', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_external_services_users', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_external_tokens', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_favourite', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_feedback', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_feedback_completed', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_feedback_completedtmp', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_feedback_item', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_feedback_sitecourse_map', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_feedback_template', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_feedback_value', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_feedback_valuetmp', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_file_conversion', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_files', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_files_reference', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_filter_active', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_filter_config', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_folder', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_forum', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_forum_digests', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_forum_discussion_subs', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_forum_discussions', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_forum_posts', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_forum_queue', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_forum_read', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_forum_subscriptions', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_forum_track_prefs', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_glossary', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_glossary_alias', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_glossary_categories', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_glossary_entries', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_glossary_entries_categories', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_glossary_formats', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_grade_categories', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_grade_categories_history', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_grade_grades', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_grade_grades_history', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_grade_import_newitem', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_grade_import_values', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_grade_items', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_grade_items_history', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_grade_letters', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_grade_outcomes', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_grade_outcomes_courses', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_grade_outcomes_history', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_grade_settings', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_grading_areas', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_grading_definitions', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_grading_instances', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_gradingform_guide_comments', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_gradingform_guide_criteria', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('moodle', 'public', 'mdl_gradingform_guide_fillings', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),

In [18]:
MIT = ['mdl_logstore_standard_log',
'mdl_context',
'mdl_user',
'mdl_course',
'mdl_modules', 
'mdl_course_modules',
'mdl_course_modules_completion', 
'mdl_grade_items',
'mdl_grade_grades',
'mdl_grade_categories',
'mdl_grade_items_history',
'mdl_grade_grades_history',
'mdl_grade_categories_history',
'mdl_forum',
'mdl_forum_discussions',
'mdl_forum_posts']

### The number of records in each of the tables given in the MIT section

In [91]:
%%sql
SELECT COUNT(*) 
FROM  mdl_logstore_standard_log

 * postgresql://postgres:***@localhost/moodle
1 rows affected.

[(417554,)]

In [106]:
%%sql
select * from mdl_logstore_standard_log limit 5

 * postgresql://postgres:***@localhost/moodle
5 rows affected.

[(1, '\\core\\event\\course_viewed', 'core', 'viewed', 'course', None, None, 'r', 2, 2, 50, 1, 0, 1, None, 0, 'N;', 1548311114, 'web', '105.233.48.139', None),
 (2, '\\core\\event\\user_loggedin', 'core', 'loggedin', 'user', 'user', 2, 'r', 0, 1, 10, 0, 2, 0, None, 0, 'a:1:{s:8:"username";s:5:"admin";}', 1548311148, 'web', '105.233.48.139', None),
 (3, '\\core\\event\\dashboard_viewed', 'core', 'viewed', 'dashboard', None, None, 'r', 0, 5, 30, 2, 2, 0, 2, 0, 'N;', 1548311179, 'web', '105.233.48.139', None),
 (4, '\\core\\event\\course_viewed', 'core', 'viewed', 'course', None, None, 'r', 2, 2, 50, 1, 0, 1, None, 0, 'N;', 1548313994, 'web', '105.233.48.139', None),
 (5, '\\core\\event\\course_viewed', 'core', 'viewed', 'course', None, None, 'r', 2, 2, 50, 1, 0, 1, None, 0, 'N;', 1548319150, 'web', '41.13.254.147', None)]

In [9]:
%%sql
SELECT COUNT(*) FROM  mdl_context

 * postgresql://postgres:***@localhost/moodle
1 rows affected.

[(4359,)]

In [11]:
%%sql
select * from mdl_context limit 5

 * postgresql://postgres:***@localhost/moodle
5 rows affected.

[(1, 10, 0, '/1', 1, 0),
 (496, 70, 226, '/1/72/430/496', 4, 0),
 (2, 50, 1, '/1/2', 2, 0),
 (3, 40, 1, '/1/3', 2, 0),
 (499, 70, 228, '/1/72/498/499', 4, 0)]

In [12]:
%%sql
SELECT COUNT(*) FROM  mdl_user

 * postgresql://postgres:***@localhost/moodle
1 rows affected.

[(1052,)]

In [13]:
%%sql
select * from mdl_user limit 5

 * postgresql://postgres:***@localhost/moodle
5 rows affected.

[(1, 1, 0, 0, 0, '', 'Germany', 'en', 0, 0, 0, 0, '', 'Male', 'DE'),
 (20, 1, 0, 0, 0, '', 'Germany', 'en', 1549745767, 1562935333, 1549745767, 1562935333, '197.215.32.111', 'Male', 'DE'),
 (15, 1, 0, 0, 0, '', 'Germany', 'en', 1549633236, 1563537002, 1563469481, 1563537002, '41.184.239.200', 'Male', 'DE'),
 (36, 1, 0, 0, 0, '', 'Ghana', 'en', 1549641288, 1559227964, 1549651186, 1559227892, '154.160.1.224', 'Male', 'GH'),
 (44, 1, 0, 0, 0, '', 'Ghana', 'en', 1549637001, 1560095090, 1557475553, 1560094908, '129.122.1.14', 'Male', 'GH')]

In [42]:
%%sql
SELECT COUNT(*) FROM  mdl_course

 * postgresql://postgres:***@localhost/moodle
1 rows affected.

[(15,)]

In [58]:
%%sql
select * from mdl_user limit 5

 * postgresql://postgres:***@localhost/moodle
5 rows affected.

[(1, 1, 0, 0, 0, '', 'Germany', 'en', 0, 0, 0, 0, '', 'Male', 'DE'),
 (20, 1, 0, 0, 0, '', 'Germany', 'en', 1549745767, 1562935333, 1549745767, 1562935333, '197.215.32.111', 'Male', 'DE'),
 (15, 1, 0, 0, 0, '', 'Germany', 'en', 1549633236, 1563537002, 1563469481, 1563537002, '41.184.239.200', 'Male', 'DE'),
 (36, 1, 0, 0, 0, '', 'Ghana', 'en', 1549641288, 1559227964, 1549651186, 1559227892, '154.160.1.224', 'Male', 'GH'),
 (44, 1, 0, 0, 0, '', 'Ghana', 'en', 1549637001, 1560095090, 1557475553, 1560094908, '129.122.1.14', 'Male', 'GH')]

In [47]:
%%sql
SELECT COUNT(*) FROM  mdl_modules

 * postgresql://postgres:***@localhost/moodle
1 rows affected.

[(26,)]

In [59]:
%%sql
select * from mdl_user limit 5

 * postgresql://postgres:***@localhost/moodle
5 rows affected.

[(1, 1, 0, 0, 0, '', 'Germany', 'en', 0, 0, 0, 0, '', 'Male', 'DE'),
 (20, 1, 0, 0, 0, '', 'Germany', 'en', 1549745767, 1562935333, 1549745767, 1562935333, '197.215.32.111', 'Male', 'DE'),
 (15, 1, 0, 0, 0, '', 'Germany', 'en', 1549633236, 1563537002, 1563469481, 1563537002, '41.184.239.200', 'Male', 'DE'),
 (36, 1, 0, 0, 0, '', 'Ghana', 'en', 1549641288, 1559227964, 1549651186, 1559227892, '154.160.1.224', 'Male', 'GH'),
 (44, 1, 0, 0, 0, '', 'Ghana', 'en', 1549637001, 1560095090, 1557475553, 1560094908, '129.122.1.14', 'Male', 'GH')]

In [49]:
%%sql
SELECT COUNT(*) 
FROM  mdl_course_modules

 * postgresql://postgres:***@localhost/moodle
1 rows affected.

[(290,)]

In [60]:
%%sql
select * from mdl_course_modules limit 5

 * postgresql://postgres:***@localhost/moodle
5 rows affected.

[(1, 1, 9, 1, 2, None, 1548435669, 0, 0, 1, 1, 1, 0, 0, 0, None, 0, 0, 0, None, 0),
 (23, 6, 12, 1, 17, None, 1206338932, 0, 0, 1, 1, 1, 0, 0, 0, None, 0, 0, 0, None, 0),
 (69, 8, 15, 2, 29, '', 1543620947, 0, 0, 1, 1, 1, 0, 0, 0, None, 0, 0, 0, None, 0),
 (24, 6, 9, 4, 17, None, 1206338989, 0, 0, 1, 1, 1, 1, 0, 0, None, 0, 0, 0, None, 0),
 (227, 11, 9, 24, 57, None, 1549462268, 0, 0, 1, 1, 1, 0, 0, 0, None, 0, 0, 0, None, 0)]

In [65]:
%%sql
SELECT COUNT(*) 
FROM  mdl_course_modules_completion

 * postgresql://postgres:***@localhost/moodle
1 rows affected.

[(4483,)]

In [66]:
%%sql
select * from mdl_course_modules_completion limit 5

 * postgresql://postgres:***@localhost/moodle
5 rows affected.

[(5801, 224, 56, 1, 0, None, 1561988963),
 (3, 228, 3, 0, 1, None, 0),
 (36, 228, 2, 0, 1, None, 0),
 (37, 228, 5, 0, 1, None, 0),
 (38, 228, 32, 0, 1, None, 0)]

In [15]:
%%sql
SELECT COUNT(*)
from mdl_grade_grades

 * postgresql://postgres:***@localhost/moodle
1 rows affected.

[(3643,)]

In [17]:
%%sql
select * from mdl_grade_grades limit 5

 * postgresql://postgres:***@localhost/moodle
5 rows affected.

[(2, 92, 3, None, Decimal('100.00000'), Decimal('0.00000'), None, None, None, 0, 0, 0, 0, 0, 0, None, 0, None, 0, None, None, 'unknown', None),
 (1, 93, 3, None, Decimal('10.00000'), Decimal('0.00000'), None, 3, None, 0, 0, 0, 0, 0, 0, None, 0, None, 0, None, None, 'novalue', Decimal('0.00000')),
 (51, 126, 50, None, Decimal('12.00000'), Decimal('0.00000'), None, None, Decimal('12.00000'), 0, 0, 0, 0, 0, 0, None, 0, None, 0, None, 1549723271, 'unknown', None),
 (35, 92, 65, None, Decimal('12.00000'), Decimal('0.00000'), None, None, Decimal('0.00000'), 0, 0, 0, 0, 0, 0, None, 0, None, 0, None, 1549642424, 'unknown', None),
 (34, 93, 65, Decimal('0.00000'), Decimal('12.00000'), Decimal('0.00000'), None, 3, Decimal('0.00000'), 0, 0, 0, 0, 0, 0, None, 0, None, 0, 1549639813, 1549642424, 'used', Decimal('1.00000'))]

In [35]:
%%sql
SELECT COUNT(*)
from mdl_forum_posts;

 * postgresql://postgres:***@localhost/moodle
1 rows affected.

[(131,)]

In [37]:
%%sql
select * from mdl_forum_posts limit 3

 * postgresql://postgres:***@localhost/moodle
3 rows affected.

[(1, 1, 0, 2, 1548435938, 1548444475, 1, 'Deployment', '<p>This website is still in testing mode. Public release date: 28 Jan 2019! Stay tuned!</p><p><span class="edited">(Edited by <a href="https://moodle.10academy.org/user/view.php?id=3&amp;course=1">Arun Sharma</a> - original submission Friday, 25 January 2019, 6:05 PM)</span></p>', 1, 0, '', 0, 0, 0),
 (3, 3, 0, 2, 1549622897, 1549622897, 1, '2019 Potential Fellows', '<p>We are happy to announce that this platform is officially kick-started, and the 2017 10 Academy Fellows and the the first batch of the 2019 Potential Fellows are included in the system.&nbsp;<br></p><p>Exciting future ahead!</p>', 1, 0, '', 0, 0, 0),
 (4, 4, 0, 3, 1549649825, 1549649825, 1, 'New Pattern Match!', '<p>Hello, the old Pattern Match course was not functioning properly - a new course (Pattern Match (new)) has been added.&nbsp; Sorry for the hassle. -as</p>', 1, 0, '', 0, 0, 0)]

### Number of quiz submissions by hour of day

In [139]:
%%sql
select count(id),
EXTRACT(HOUR FROM to_timestamp(timecreated)) AS HOUR 
from mdl_logstore_standard_log where action='submitted' AND component='mod_quiz' 
group by EXTRACT(HOUR FROM to_timestamp(timecreated));

 * postgresql://postgres:***@localhost/moodle
24 rows affected.

[(26, 0.0),
 (23, 1.0),
 (30, 2.0),
 (29, 3.0),
 (7, 4.0),
 (14, 5.0),
 (10, 6.0),
 (18, 7.0),
 (17, 8.0),
 (34, 9.0),
 (46, 10.0),
 (69, 11.0),
 (95, 12.0),
 (88, 13.0),
 (104, 14.0),
 (90, 15.0),
 (80, 16.0),
 (68, 17.0),
 (68, 18.0),
 (70, 19.0),
 (57, 20.0),
 (55, 21.0),
 (46, 22.0),
 (53, 23.0)]

### Monthly usage time of learners who have confirmed and are not deleted

In [134]:
%%sql
SELECT id,
EXTRACT(MONTH FROM to_timestamp(SUM(lastaccess)-SUM(firstaccess))) AS MONTH,
SUM(lastaccess)-SUM(firstaccess) AS usage_time
FROM mdl_user
WHERE confirmed=1 and deleted=0 
GROUP BY id;

 * postgresql://postgres:***@localhost/moodle
1044 rows affected.

[(652, 1.0, Decimal('0')),
 (273, 2.0, Decimal('3185506')),
 (51, 1.0, Decimal('2162524')),
 (951, 1.0, Decimal('294')),
 (839, 1.0, Decimal('0')),
 (70, 4.0, Decimal('9297531')),
 (350, 1.0, Decimal('76')),
 (758, 2.0, Decimal('2970979')),
 (539, 1.0, Decimal('0')),
 (874, 1.0, Decimal('0')),
 (278, 1.0, Decimal('1026536')),
 (946, 1.0, Decimal('59941')),
 (176, 4.0, Decimal('8621019')),
 (576, 1.0, Decimal('0')),
 (1003, 1.0, Decimal('0')),
 (1045, 1.0, Decimal('0')),
 (292, 1.0, Decimal('7278')),
 (929, 1.0, Decimal('341')),
 (663, 1.0, Decimal('0')),
 (770, 1.0, Decimal('1013')),
 (271, 6.0, Decimal('14057700')),
 (22, 1.0, Decimal('1414')),
 (417, 1.0, Decimal('1189435')),
 (764, 1.0, Decimal('4591')),
 (556, 1.0, Decimal('0')),
 (529, 1.0, Decimal('0')),
 (638, 1.0, Decimal('0')),
 (791, 1.0, Decimal('0')),
 (775, 1.0, Decimal('87793')),
 (940, 1.0, Decimal('229')),
 (390, 4.0, Decimal('9147193')),
 (173, 1.0, Decimal('0')),
 (1018, 1.0, Decimal('0')),
 (42, 4.0, Decimal('9342005')),
 (189, 2.0, Decimal('3307208')),
 (876, 1.0, Decimal('0')),
 (161, 2.0, Decimal('3598689')),
 (113, 1.0, Decimal('431112')),
 (632, 1.0, Decimal('5886')),
 (658, 1.0, Decimal('0')),
 (120, 2.0, Decimal('4337689')),
 (802, 1.0, Decimal('577322')),
 (578, 1.0, Decimal('1728016')),
 (815, 1.0, Decimal('29500')),
 (695, 1.0, Decimal('0')),
 (440, 1.0, Decimal('2328452')),
 (1004, 1.0, Decimal('1247133')),
 (794, 1.0, Decimal('387273')),
 (57, 2.0, Decimal('4432428')),
 (19, 1.0, Decimal('1180119')),
 (160, 1.0, Decimal('598277')),
 (644, 1.0, Decimal('0')),
 (824, 1.0, Decimal('0')),
 (508, 1.0, Decimal('0')),
 (357, 1.0, Decimal('591')),
 (769, 1.0, Decimal('0')),
 (266, 6.0, Decimal('14281778')),
 (315, 1.0, Decimal('55308')),
 (307, 1.0, Decimal('24217')),
 (366, 1.0, Decimal('0')),
 (841, 1.0, Decimal('0')),
 (1030, 1.0, Decimal('0')),
 (91, 1.0, Decimal('0')),
 (803, 1.0, Decimal('0')),
 (305, 1.0, Decimal('42610')),
 (54, 2.0, Decimal('3721696')),
 (181, 1.0, Decimal('0')),
 (743, 1.0, Decimal('533')),
 (963, 1.0, Decimal('0')),
 (220, 1.0, Decimal('594941')),
 (823, 1.0, Decimal('0')),
 (822, 1.0, Decimal('0')),
 (400, 3.0, Decimal('7699087')),
 (1025, 1.0, Decimal('620307')),
 (241, 1.0, Decimal('1211579')),
 (175, 1.0, Decimal('363767')),
 (1007, 1.0, Decimal('121896')),
 (596, 1.0, Decimal('0')),
 (285, 1.0, Decimal('426687')),
 (50, 4.0, Decimal('8084345')),
 (13, 1.0, Decimal('0')),
 (391, 1.0, Decimal('199')),
 (487, 1.0, Decimal('0')),
 (2, 6.0, Decimal('15243521')),
 (699, 1.0, Decimal('0')),
 (246, 6.0, Decimal('14059158')),
 (75, 1.0, Decimal('667520')),
 (128, 1.0, Decimal('474')),
 (714, 2.0, Decimal('2688364')),
 (344, 5.0, Decimal('11574727')),
 (906, 1.0, Decimal('0')),
 (909, 1.0, Decimal('0')),
 (745, 1.0, Decimal('221')),
 (534, 1.0, Decimal('2545')),
 (152, 1.0, Decimal('363926')),
 (1049, 1.0, Decimal('0')),
 (428, 3.0, Decimal('6656831')),
 (637, 1.0, Decimal('0')),
 (355, 1.0, Decimal('0')),
 (747, 3.0, Decimal('5553018')),
 (222, 2.0, Decimal('3377258')),
 (1006, 1.0, Decimal('224')),
 (1008, 1.0, Decimal('0')),
 (777, 1.0, Decimal('2562')),
 (164, 1.0, Decimal('1310')),
 (922, 1.0, Decimal('220135')),
 (453, 1.0, Decimal('8254')),
 (787, 1.0, Decimal('0')),
 (186, 1.0, Decimal('2254783')),
 (501, 1.0, Decimal('1208')),
 (750, 1.0, Decimal('78131')),
 (545, 1.0, Decimal('0')),
 (182, 2.0, Decimal('3462444')),
 (977, 1.0, Decimal('0')),
 (18, 1.0, Decimal('0')),
 (528, 1.0, Decimal('119')),
 (27, 1.0, Decimal('0')),
 (811, 1.0, Decimal('0')),
 (563, 1.0, Decimal('0')),
 (143, 3.0, Decimal('5792080')),
 (496, 1.0, Decimal('0')),
 (58, 5.0, Decimal('12820177')),
 (228, 6.0, Decimal('13584355')),
 (667, 1.0, Decimal('2131')),
 (814, 1.0, Decimal('282')),
 (668, 1.0, Decimal('0')),
 (850, 1.0, Decimal('0')),
 (294, 3.0, Decimal('7649428')),
 (481, 1.0, Decimal('0')),
 (926, 1.0, Decimal('954')),
 (645, 1.0, Decimal('0')),
 (1009, 1.0, Decimal('0')),
 (607, 4.0, Decimal('7940318')),
 (438, 1.0, Decimal('0')),
 (382, 3.0, Decimal('6377399')),
 (258, 1.0, Decimal('1518270')),
 (853, 1.0, Decimal('0')),
 (378, 1.0, Decimal('1616598')),
 (483, 1.0, Decimal('0')),
 (1050, 1.0, Decimal('0')),
 (84, 1.0, Decimal('521205')),
 (799, 1.0, Decimal('438')),
 (276, 1.0, Decimal('0')),
 (646, 1.0, Decimal('223')),
 (1044, 1.0, Decimal('0')),
 (379, 1.0, Decimal('4649')),
 (320, 1.0, Decimal('956597')),
 (942, 1.0, Decimal('0')),
 (115, 5.0, Decimal('12521978')),
 (97, 1.0, Decimal('0')),
 (108, 1.0, Decimal('617669')),
 (59, 1.0, Decimal('1614979')),
 (589, 1.0, Decimal('0')),
 (127, 2.0, Decimal('3359333')),
 (555, 1.0, Decimal('4977')),
 (682, 1.0, Decimal('82')),
 (567, 1.0, Decimal('1490157')),
 (329, 1.0, Decimal('0')),
 (44, 5.0, Decimal('10458089')),
 (816, 1.0, Decimal('0')),
 (676, 1.0, Decimal('1134850')),
 (153, 1.0, Decimal('438636')),
 (778, 1.0, Decimal('0')),
 (507, 1.0, Decimal('0')),
 (1022, 1.0, Decimal('0')),
 (944, 1.0, Decimal('0')),
 (214, 1.0, Decimal('1301042')),
 (847, 1.0, Decimal('18346')),
 (419, 1.0, Decimal('76621')),
 (664, 1.0, Decimal('0')),
 (551, 1.0, Decimal('0')),
 (532, 1.0, Decimal('66')),
 (945, 1.0, Decimal('850985')),
 (948, 1.0, Decimal('0')),
 (95, 6.0, Decimal('13138743')),
 (259, 4.0, Decimal('8773696')),
 (519, 1.0, Decimal('0')),
 (965, 1.0, Decimal('0')),
 (172, 1.0, Decimal('198')),
 (409, 4.0, Decimal('8372577')),
 (840, 1.0, Decimal('138')),
 (30, 1.0, Decimal('26700')),
 (521, 1.0, Decimal('0')),
 (1038, 1.0, Decimal('0')),
 (3, 7.0, Decimal('15988837')),
 (936, 1.0, Decimal('0')),
 (324, 1.0, Decimal('0')),
 (981, 1.0, Decimal('0')),
 (921, 1.0, Decimal('2650')),
 (249, 1.0, Decimal('0')),
 (255, 1.0, Decimal('89447')),
 (984, 1.0, Decimal('0')),
 (209, 3.0, Decimal('5582985')),
 (639, 1.0, Decimal('0')),
 (296, 1.0, Decimal('992847')),
 (74, 1.0, Decimal('1189220')),
 (937, 1.0, Decimal('0')),
 (868, 1.0, Decimal('0')),
 (138, 4.0, Decimal('8600948')),
 (418, 1.0, Decimal('0')),
 (947, 1.0, Decimal('0')),
 (978, 1.0, Decimal('0')),
 (972, 1.0, Decimal('0')),
 (761, 1.0, Decimal('0')),
 (407, 1.0, Decimal('228')),
 (90, 5.0, Decimal('13009264')),
 (904, 1.0, Decimal('98')),
 (443, 1.0, Decimal('62136')),
 (387, 1.0, Decimal('1745757')),
 (39, 2.0, Decimal('3181706')),
 (690, 1.0, Decimal('0')),
 (526, 1.0, Decimal('290')),
 (393, 1.0, Decimal('0')),
 (524, 1.0, Decimal('251')),
 (312, 1.0, Decimal('0')),
 (498, 1.0, Decimal('0')),
 (862, 1.0, Decimal('2959')),
 (494, 1.0, Decimal('567')),
 (469, 1.0, Decimal('0')),
 (683, 2.0, Decimal('3748128')),
 (118, 3.0, Decimal('5810046')),
 (317, 5.0, Decimal('10602415')),
 (793, 1.0, Decimal('350')),
 (608, 1.0, Decimal('1724349')),
 (702, 1.0, Decimal('0')),
 (488, 1.0, Decimal('0')),
 (1048, 1.0, Decimal('345')),
 (126, 4.0, Decimal('9475150')),
 (194, 2.0, Decimal('3106802')),
 (360, 1.0, Decimal('0')),
 (463, 1.0, Decimal('0')),
 (476, 1.0, Decimal('104776')),
 (99, 2.0, Decimal('4124510')),
 (883, 1.0, Decimal('0')),
 (629, 1.0, Decimal('0')),
 (726, 3.0, Decimal('5676724')),
 (374, 1.0, Decimal('803852')),
 (224, 1.0, Decimal('0')),
 (719, 1.0, Decimal('0')),
 (756, 1.0, Decimal('602')),
 (318, 1.0, Decimal('933034')),
 (933, 1.0, Decimal('0')),
 (647, 1.0, Decimal('0')),
 (442, 1.0, Decimal('0')),
 (354, 3.0, Decimal('6318386')),
 (593, 1.0, Decimal('1277628')),
 (12, 1.0, Decimal('0')),
 (479, 1.0, Decimal('83')),
 (293, 1.0, Decimal('1548005')),
 (495, 1.0, Decimal('1339')),
 (154, 1.0, Decimal('0')),
 (657, 1.0, Decimal('0')),
 (234, 5.0, Decimal('11671068')),
 (474, 1.0, Decimal('0')),
 (899, 1.0, Decimal('0')),
 (935, 1.0, Decimal('0')),
 (675, 1.0, Decimal('0')),
 (748, 1.0, Decimal('1962194')),
 (696, 1.0, Decimal('0')),
 (969, 1.0, Decimal('0')),
 (264, 1.0, Decimal('706')),
 (270, 1.0, Decimal('393476')),
 (898, 1.0, Decimal('0')),
 (435, 1.0, Decimal('0')),
 (384, 3.0, Decimal('5524196')),
 (351, 1.0, Decimal('2471289')),
 (116, 1.0, Decimal('775232')),
 (970, 1.0, Decimal('0')),
 (732, 1.0, Decimal('425')),
 (837, 1.0, Decimal('0')),
 (826, 1.0, Decimal('168121')),
 (431, 1.0, Decimal('1282123')),
 (911, 1.0, Decimal('6349')),
 (491, 1.0, Decimal('0')),
 (462, 1.0, Decimal('0')),
 (734, 1.0, Decimal('8329')),
 (855, 1.0, Decimal('0')),
 (436, 1.0, Decimal('1281659')),
 (180, 2.0, Decimal('3101799')),
 (967, 1.0, Decimal('0')),
 (870, 1.0, Decimal('382')),
 (626, 1.0, Decimal('0')),
 (263, 1.0, Decimal('1504051')),
 (836, 1.0, Decimal('0')),
 (784, 1.0, Decimal('162')),
 (711, 1.0, Decimal('0')),
 (470, 3.0, Decimal('6046578')),
 (780, 1.0, Decimal('58285')),
 (768, 1.0, Decimal('0')),
 (1036, 1.0, Decimal('0')),
 (838, 1.0, Decimal('169050')),
 (149, 3.0, Decimal('7026643')),
 (478, 1.0, Decimal('0')),
 (577, 1.0, Decimal('0')),
 (505, 1.0, Decimal('1323429')),
 (280, 2.0, Decimal('3421123')),
 (88, 3.0, Decimal('6003700')),
 (188, 1.0, Decimal('435195')),
 (461, 1.0, Decimal('2487701')),
 (240, 1.0, Decimal('313')),
 (328, 4.0, Decimal('8808737')),
 (717, 1.0, Decimal('0')),
 (525, 1.0, Decimal('8039')),
 (634, 1.0, Decimal('0')),
 (1046, 1.0, Decimal('0')),
 (650, 3.0, Decimal('7201853')),
 (703, 1.0, Decimal('0')),
 (210, 3.0, Decimal('5581926')),
 (226, 1.0, Decimal('138')),
 (48, 6.0, Decimal('14463911')),
 (843, 1.0, Decimal('134951')),
 (710, 1.0, Decimal('0')),
 (1016, 1.0, Decimal('597')),
 (447, 1.0, Decimal('0')),
 (298, 1.0, Decimal('2252501')),
 (81, 1.0, Decimal('378150')),
 (1015, 1.0, Decimal('361')),
 (954, 1.0, Decimal('0')),
 (800, 1.0, Decimal('0')),
 (204, 2.0, Decimal('3492781')),
 (1021, 1.0, Decimal('0')),
 (5, 6.0, Decimal('13523007')),
 (456, 1.0, Decimal('0')),
 (796, 2.0, Decimal('4890303')),
 (531, 1.0, Decimal('0')),
 (283, 1.0, Decimal('0')),
 (807, 1.0, Decimal('1781788')),
 (624, 1.0, Decimal('0')),
 (546, 1.0, Decimal('0')),
 (686, 3.0, Decimal('6990596')),
 (297, 1.0, Decimal('3807')),
 (361, 5.0, Decimal('10806143')),
 (681, 1.0, Decimal('0')),
 (303, 5.0, Decimal('11822787')),
 (974, 1.0, Decimal('0')),
 (829, 1.0, Decimal('0')),
 (785, 1.0, Decimal('1270412')),
 (643, 1.0, Decimal('0')),
 (472, 1.0, Decimal('0')),
 (444, 1.0, Decimal('0')),
 (537, 1.0, Decimal('0')),
 (233, 1.0, Decimal('1824809')),
 (89, 1.0, Decimal('0')),
 (93, 1.0, Decimal('324556')),
 (373, 1.0, Decimal('2254')),
 (252, 1.0, Decimal('423053')),
 (343, 1.0, Decimal('56048')),
 (31, 1.0, Decimal('0')),
 (723, 2.0, Decimal('3533540')),
 (497, 2.0, Decimal('2697053')),
 (884, 1.0, Decimal('0')),
 (155, 1.0, Decimal('156')),
 (722, 1.0, Decimal('0')),
 (953, 1.0, Decimal('441')),
 (609, 1.0, Decimal('0')),
 (416, 2.0, Decimal('4783021')),
 (195, 1.0, Decimal('6528')),
 (199, 3.0, Decimal('7427025')),
 (369, 5.0, Decimal('11589135')),
 (441, 1.0, Decimal('0')),
 (243, 1.0, Decimal('2799')),
 (902, 1.0, Decimal('0')),
 (1047, 1.0, Decimal('231000')),
 (740, 1.0, Decimal('0')),
 (892, 1.0, Decimal('0')),
 (856, 1.0, Decimal('1311324')),
 (230, 1.0, Decimal('0')),
 (503, 1.0, Decimal('0')),
 (78, 1.0, Decimal('5638')),
 (573, 1.0, Decimal('0')),
 (987, 1.0, Decimal('398')),
 (994, 1.0, Decimal('0')),
 (852, 1.0, Decimal('0')),
 (250, 6.0, Decimal('13165098')),
 (611, 4.0, Decimal('8042954')),
 (621, 1.0, Decimal('0')),
 (865, 3.0, Decimal('6101562')),
 (962, 1.0, Decimal('0')),
 (106, 5.0, Decimal('11135377')),
 (1010, 1.0, Decimal('839763')),
 (178, 2.0, Decimal('3282138')),
 (795, 1.0, Decimal('1500450')),
 (809, 1.0, Decimal('589')),
 (585, 1.0, Decimal('0')),
 (8, 1.0, Decimal('1830649')),
 (934, 1.0, Decimal('0')),
 (908, 1.0, Decimal('12619')),
 (708, 1.0, Decimal('0')),
 (455, 3.0, Decimal('5464762')),
 (370, 1.0, Decimal('1472')),
 (684, 1.0, Decimal('0')),
 (713, 1.0, Decimal('0')),
 (448, 1.0, Decimal('1797')),
 (930, 2.0, Decimal('3113356')),
 (396, 3.0, Decimal('6052383')),
 (701, 1.0, Decimal('0')),
 (132, 2.0, Decimal('3229451')),
 (514, 1.0, Decimal('0')),
 (322, 1.0, Decimal('150')),
 (854, 1.0, Decimal('544')),
 (389, 1.0, Decimal('0')),
 (916, 1.0, Decimal('0')),
 (863, 1.0, Decimal('0')),
 (114, 1.0, Decimal('0')),
 (60, 5.0, Decimal('12695975')),
 (1052, 1.0, Decimal('0')),
 (754, 1.0, Decimal('2342942')),
 (518, 1.0, Decimal('0')),
 (289, 2.0, Decimal('3780455')),
 (65, 5.0, Decimal('11849928')),
 (583, 1.0, Decimal('0')),
 (693, 1.0, Decimal('0')),
 (98, 5.0, Decimal('12944059')),
 (744, 1.0, Decimal('1262')),
 (715, 1.0, Decimal('0')),
 (527, 1.0, Decimal('0')),
 (490, 1.0, Decimal('395')),
 (235, 1.0, Decimal('5433')),
 (763, 1.0, Decimal('0')),
 (627, 1.0, Decimal('675650')),
 (119, 1.0, Decimal('499835')),
 (306, 5.0, Decimal('10860048')),
 (286, 5.0, Decimal('11526055')),
 (376, 1.0, Decimal('889945')),
 (147, 6.0, Decimal('13149714')),
 (860, 1.0, Decimal('0')),
 (480, 3.0, Decimal('7089246')),
 (338, 1.0, Decimal('0')),
 (358, 1.0, Decimal('0')),
 (412, 1.0, Decimal('0')),
 (989, 1.0, Decimal('1127202')),
 (26, 1.0, Decimal('0')),
 (950, 1.0, Decimal('0')),
 (564, 2.0, Decimal('2839046')),
 (535, 1.0, Decimal('265')),
 (72, 1.0, Decimal('293')),
 (642, 1.0, Decimal('169')),
 (232, 1.0, Decimal('659')),
 (77, 4.0, Decimal('8924693')),
 (725, 1.0, Decimal('0')),
 (131, 1.0, Decimal('779553')),
 (310, 1.0, Decimal('0')),
 (37, 1.0, Decimal('0')),
 (832, 1.0, Decimal('0')),
 (907, 1.0, Decimal('0')),
 (1001, 1.0, Decimal('6483')),
 (584, 1.0, Decimal('2020')),
 (746, 1.0, Decimal('0')),
 (806, 1.0, Decimal('0')),
 (353, 2.0, Decimal('4094779')),
 (939, 1.0, Decimal('32548')),
 (834, 1.0, Decimal('484')),
 (831, 1.0, Decimal('0')),
 (813, 1.0, Decimal('4187')),
 (574, 1.0, Decimal('279')),
 (225, 1.0, Decimal('1347959')),
 (333, 1.0, Decimal('757')),
 (45, 6.0, Decimal('13809300')),
 (174, 3.0, Decimal('6846708')),
 (891, 1.0, Decimal('0')),
 (134, 1.0, Decimal('503')),
 (918, 2.0, Decimal('2676389')),
 (975, 1.0, Decimal('0')),
 (36, 4.0, Decimal('9586676')),
 (848, 1.0, Decimal('1312')),
 (102, 3.0, Decimal('6402066')),
 (430, 1.0, Decimal('0')),
 (158, 4.0, Decimal('8307972')),
 (533, 1.0, Decimal('149')),
 (915, 1.0, Decimal('0')),
 (459, 1.0, Decimal('348')),
 (207, 1.0, Decimal('642')),
 (979, 1.0, Decimal('0')),
 (123, 6.0, Decimal('13116129')),
 (871, 1.0, Decimal('0')),
 (881, 1.0, Decimal('393')),
 (385, 5.0, Decimal('11859662')),
 (492, 1.0, Decimal('0')),
 (544, 1.0, Decimal('0')),
 (365, 1.0, Decimal('0')),
 (704, 1.0, Decimal('0')),
 (157, 1.0, Decimal('309361')),
 (606, 1.0, Decimal('0')),
 (308, 1.0, Decimal('191')),
 (618, 1.0, Decimal('174')),
 (880, 1.0, Decimal('0')),
 (313, 4.0, Decimal('9504563')),
 (140, 1.0, Decimal('867280')),
 (248, 1.0, Decimal('0')),
 (137, 1.0, Decimal('528748')),
 (208, 4.0, Decimal('8619570')),
 (614, 1.0, Decimal('682')),
 (392, 1.0, Decimal('2190435')),
 (24, 4.0, Decimal('9916251')),
 (191, 1.0, Decimal('0')),
 (966, 1.0, Decimal('0')),
 (760, 1.0, Decimal('709504')),
 (94, 1.0, Decimal('1549961')),
 (218, 1.0, Decimal('0')),
 (49, 1.0, Decimal('0')),
 (671, 1.0, Decimal('0')),
 (580, 1.0, Decimal('0')),
 (742, 1.0, Decimal('1356126')),
 (912, 1.0, Decimal('0')),
 (846, 1.0, Decimal('1688659')),
 (938, 1.0, Decimal('0')),
 (1037, 1.0, Decimal('0')),
 (184, 1.0, Decimal('1857706')),
 (87, 1.0, Decimal('0')),
 (753, 1.0, Decimal('0')),
 (477, 1.0, Decimal('0')),
 (550, 1.0, Decimal('0')),
 (394, 1.0, Decimal('25773')),
 (272, 2.0, Decimal('4489877')),
 (781, 1.0, Decimal('0')),
 (867, 1.0, Decimal('501133')),
 (190, 6.0, Decimal('13469600')),
 (858, 1.0, Decimal('0')),
 (554, 1.0, Decimal('232')),
 (406, 2.0, Decimal('2794812')),
 (424, 3.0, Decimal('6040133')),
 (670, 1.0, Decimal('0')),
 (309, 4.0, Decimal('9454930')),
 (849, 1.0, Decimal('6443')),
 (509, 1.0, Decimal('2404')),
 (919, 1.0, Decimal('4572')),
 (156, 3.0, Decimal('5683901')),
 (932, 1.0, Decimal('0')),
 (475, 1.0, Decimal('1139475')),
 (641, 1.0, Decimal('0')),
 (961, 1.0, Decimal('0')),
 (888, 1.0, Decimal('835')),
 (282, 2.0, Decimal('3011233')),
 (733, 1.0, Decimal('1207675')),
 (269, 3.0, Decimal('6355099')),
 (261, 1.0, Decimal('898')),
 (502, 1.0, Decimal('14004')),
 (117, 1.0, Decimal('0')),
 (125, 5.0, Decimal('11992361')),
 (257, 1.0, Decimal('0')),
 (40, 2.0, Decimal('3810757')),
 (700, 1.0, Decimal('500')),
 (43, 4.0, Decimal('9245133')),
 (587, 1.0, Decimal('389')),
 (349, 2.0, Decimal('3736891')),
 (187, 1.0, Decimal('0')),
 (914, 1.0, Decimal('4638')),
 (766, 2.0, Decimal('4595794')),
 (728, 1.0, Decimal('0')),
 (506, 1.0, Decimal('0')),
 (242, 2.0, Decimal('3038881')),
 (331, 5.0, Decimal('10980780')),
 (1024, 1.0, Decimal('0')),
 (913, 1.0, Decimal('144')),
 (599, 1.0, Decimal('0')),
 (677, 1.0, Decimal('0')),
 (1028, 1.0, Decimal('50577')),
 (29, 1.0, Decimal('0')),
 (698, 1.0, Decimal('0')),
 (96, 1.0, Decimal('500383')),
 (466, 1.0, Decimal('0')),
 (201, 5.0, Decimal('12782407')),
 (844, 1.0, Decimal('227662')),
 (980, 1.0, Decimal('0')),
 (1039, 1.0, Decimal('0')),
 (631, 3.0, Decimal('6530302')),
 (107, 3.0, Decimal('6915515')),
 (446, 1.0, Decimal('0')),
 (749, 1.0, Decimal('607021')),
 (86, 1.0, Decimal('400356')),
 (920, 1.0, Decimal('0')),
 (219, 1.0, Decimal('152065')),
 (363, 2.0, Decimal('3112743')),
 (231, 1.0, Decimal('19926')),
 (66, 1.0, Decimal('0')),
 (661, 1.0, Decimal('0')),
 (340, 3.0, Decimal('6414257')),
 (512, 3.0, Decimal('5980583')),
 (873, 1.0, Decimal('1153488')),
 (523, 1.0, Decimal('0')),
 (356, 1.0, Decimal('16802')),
 (458, 1.0, Decimal('0')),
 (414, 1.0, Decimal('1393')),
 (640, 1.0, Decimal('0')),
 (368, 1.0, Decimal('0')),
 (735, 1.0, Decimal('0')),
 (538, 1.0, Decimal('0')),
 (166, 1.0, Decimal('2057951')),
 (595, 1.0, Decimal('2203')),
 (142, 1.0, Decimal('0')),
 (924, 1.0, Decimal('1795355')),
 (872, 1.0, Decimal('0')),
 (410, 4.0, Decimal('8467897')),
 (792, 1.0, Decimal('0')),
 (896, 1.0, Decimal('702')),
 (651, 1.0, Decimal('0')),
 (381, 5.0, Decimal('10647918')),
 (38, 4.0, Decimal('9936188')),
 (1005, 1.0, Decimal('418')),
 (359, 1.0, Decimal('938850')),
 (597, 1.0, Decimal('0')),
 (193, 1.0, Decimal('374155')),
 (1012, 1.0, Decimal('0')),
 (730, 1.0, Decimal('846')),
 (548, 1.0, Decimal('87106')),
 (217, 4.0, Decimal('9255271')),
 (709, 1.0, Decimal('0')),
 (47, 2.0, Decimal('3727375')),
 (886, 1.0, Decimal('0')),
 (177, 1.0, Decimal('0')),
 (727, 1.0, Decimal('262')),
 (985, 1.0, Decimal('0')),
 (810, 1.0, Decimal('0')),
 (779, 1.0, Decimal('0')),
 (110, 1.0, Decimal('45')),
 (931, 1.0, Decimal('1971')),
 (145, 4.0, Decimal('8611820')),
 (557, 3.0, Decimal('6799379')),
 (718, 1.0, Decimal('14211')),
 (485, 1.0, Decimal('0')),
 (623, 1.0, Decimal('0')),
 (229, 1.0, Decimal('0')),
 (559, 3.0, Decimal('6667415')),
 (788, 1.0, Decimal('0')),
 (304, 1.0, Decimal('0')),
 (52, 1.0, Decimal('20253')),
 (633, 1.0, Decimal('0')),
 (341, 2.0, Decimal('3272673')),
 (450, 1.0, Decimal('0')),
 (900, 1.0, Decimal('0')),
 (405, 1.0, Decimal('0')),
 (170, 6.0, Decimal('13583363')),
 (996, 1.0, Decimal('0')),
 (762, 1.0, Decimal('0')),
 (712, 1.0, Decimal('169')),
 (192, 1.0, Decimal('0')),
 (513, 1.0, Decimal('500')),
 (101, 1.0, Decimal('1403')),
 (473, 3.0, Decimal('5446904')),
 (69, 1.0, Decimal('92891')),
 (878, 1.0, Decimal('13974')),
 (679, 1.0, Decimal('0')),
 (983, 1.0, Decimal('0')),
 (375, 1.0, Decimal('3481')),
 (415, 1.0, Decimal('0')),
 (729, 3.0, Decimal('5793789')),
 (976, 1.0, Decimal('610')),
 (680, 1.0, Decimal('0')),
 (408, 1.0, Decimal('0')),
 (782, 1.0, Decimal('0')),
 (689, 1.0, Decimal('0')),
 (982, 1.0, Decimal('0')),
 (522, 1.0, Decimal('1815006')),
 (674, 1.0, Decimal('0')),
 (630, 1.0, Decimal('277')),
 (575, 1.0, Decimal('0')),
 (821, 1.0, Decimal('0')),
 (401, 1.0, Decimal('0')),
 (659, 1.0, Decimal('1907951')),
 (739, 1.0, Decimal('0')),
 (279, 1.0, Decimal('0')),
 (9, 5.0, Decimal('12451461')),
 (903, 1.0, Decimal('580151')),
 (741, 1.0, Decimal('1174')),
 (716, 1.0, Decimal('0')),
 (897, 1.0, Decimal('160020')),
 (543, 1.0, Decimal('104')),
 (565, 1.0, Decimal('346609')),
 (736, 1.0, Decimal('0')),
 (566, 1.0, Decimal('256')),
 (457, 1.0, Decimal('0')),
 (85, 1.0, Decimal('9452')),
 (592, 1.0, Decimal('0')),
 (281, 1.0, Decimal('172033')),
 (687, 1.0, Decimal('0')),

### Count of log events per user for the actions

In [131]:
%%sql
SELECT id, count(*)
FROM mdl_logstore_standard_log
WHERE action = 'loggedin'
GROUP BY id

 * postgresql://postgres:***@localhost/moodle
4444 rows affected.

[(2, 1),
 (10, 1),
 (28, 1),
 (30, 1),
 (46, 1),
 (52, 1),
 (64, 1),
 (69, 1),
 (73, 1),
 (89, 1),
 (103, 1),
 (106, 1),
 (124, 1),
 (131, 1),
 (140, 1),
 (144, 1),
 (162, 1),
 (221, 1),
 (253, 1),
 (264, 1),
 (276, 1),
 (289, 1),
 (303, 1),
 (317, 1),
 (325, 1),
 (339, 1),
 (362, 1),
 (455, 1),
 (559, 1),
 (579, 1),
 (581, 1),
 (583, 1),
 (593, 1),
 (635, 1),
 (652, 1),
 (1028, 1),
 (1033, 1),
 (1035, 1),
 (1088, 1),
 (1190, 1),
 (1201, 1),
 (1240, 1),
 (1272, 1),
 (1294, 1),
 (1357, 1),
 (1385, 1),
 (1415, 1),
 (1469, 1),
 (1473, 1),
 (1627, 1),
 (1652, 1),
 (1787, 1),
 (1804, 1),
 (1866, 1),
 (1919, 1),
 (1921, 1),
 (1957, 1),
 (2019, 1),
 (2174, 1),
 (2199, 1),
 (2290, 1),
 (2350, 1),
 (2411, 1),
 (2458, 1),
 (2471, 1),
 (2494, 1),
 (3031, 1),
 (3033, 1),
 (3063, 1),
 (3078, 1),
 (3097, 1),
 (3143, 1),
 (3156, 1),
 (3158, 1),
 (3187, 1),
 (3219, 1),
 (3255, 1),
 (3261, 1),
 (3263, 1),
 (3280, 1),
 (3287, 1),
 (3347, 1),
 (3366, 1),
 (3371, 1),
 (3420, 1),
 (3427, 1),
 (3513, 1),
 (3586, 1),
 (3620, 1),
 (3796, 1),
 (3944, 1),
 (3954, 1),
 (4059, 1),
 (4074, 1),
 (4127, 1),
 (4142, 1),
 (4146, 1),
 (4177, 1),
 (4188, 1),
 (4190, 1),
 (4244, 1),
 (4324, 1),
 (4330, 1),
 (4339, 1),
 (4352, 1),
 (4363, 1),
 (4372, 1),
 (4398, 1),
 (4410, 1),
 (4422, 1),
 (4475, 1),
 (4483, 1),
 (4488, 1),
 (4495, 1),
 (4540, 1),
 (4548, 1),
 (4563, 1),
 (4579, 1),
 (4616, 1),
 (4621, 1),
 (4647, 1),
 (4656, 1),
 (4691, 1),
 (4768, 1),
 (4769, 1),
 (4776, 1),
 (4792, 1),
 (4814, 1),
 (4848, 1),
 (4853, 1),
 (4862, 1),
 (5017, 1),
 (5030, 1),
 (5061, 1),
 (5072, 1),
 (5090, 1),
 (5093, 1),
 (5139, 1),
 (5146, 1),
 (5148, 1),
 (5154, 1),
 (5157, 1),
 (5160, 1),
 (5165, 1),
 (5215, 1),
 (5227, 1),
 (5240, 1),
 (5258, 1),
 (5273, 1),
 (5302, 1),
 (5341, 1),
 (5352, 1),
 (5380, 1),
 (5389, 1),
 (5404, 1),
 (5458, 1),
 (5465, 1),
 (5480, 1),
 (5521, 1),
 (5557, 1),
 (5564, 1),
 (5570, 1),
 (5622, 1),
 (5649, 1),
 (5692, 1),
 (5730, 1),
 (5757, 1),
 (5768, 1),
 (5775, 1),
 (5779, 1),
 (5783, 1),
 (5788, 1),
 (5795, 1),
 (5938, 1),
 (6021, 1),
 (6077, 1),
 (6094, 1),
 (6099, 1),
 (6145, 1),
 (6152, 1),
 (6204, 1),
 (6216, 1),
 (6221, 1),
 (6259, 1),
 (6279, 1),
 (6283, 1),
 (6388, 1),
 (6394, 1),
 (6418, 1),
 (6423, 1),
 (6433, 1),
 (6457, 1),
 (6479, 1),
 (6480, 1),
 (6487, 1),
 (6597, 1),
 (6990, 1),
 (7001, 1),
 (7019, 1),
 (7028, 1),
 (7038, 1),
 (7067, 1),
 (7075, 1),
 (7099, 1),
 (7122, 1),
 (7145, 1),
 (7155, 1),
 (7203, 1),
 (7297, 1),
 (7313, 1),
 (7323, 1),
 (10283, 1),
 (10313, 1),
 (10316, 1),
 (10318, 1),
 (10321, 1),
 (10350, 1),
 (10356, 1),
 (10378, 1),
 (10386, 1),
 (10396, 1),
 (10427, 1),
 (10434, 1),
 (10457, 1),
 (10480, 1),
 (10493, 1),
 (10495, 1),
 (10499, 1),
 (10519, 1),
 (10522, 1),
 (10559, 1),
 (10580, 1),
 (10582, 1),
 (10601, 1),
 (10602, 1),
 (10604, 1),
 (10649, 1),
 (10677, 1),
 (10686, 1),
 (10696, 1),
 (10699, 1),
 (10744, 1),
 (10748, 1),
 (10797, 1),
 (10808, 1),
 (10824, 1),
 (10846, 1),
 (10853, 1),
 (10871, 1),
 (10878, 1),
 (10880, 1),
 (11025, 1),
 (11033, 1),
 (11055, 1),
 (11086, 1),
 (11089, 1),
 (11113, 1),
 (11121, 1),
 (11148, 1),
 (11167, 1),
 (11178, 1),
 (11185, 1),
 (11192, 1),
 (11205, 1),
 (11240, 1),
 (11242, 1),
 (11276, 1),
 (11296, 1),
 (11320, 1),
 (11339, 1),
 (11376, 1),
 (11405, 1),
 (11463, 1),
 (11491, 1),
 (11493, 1),
 (11501, 1),
 (11503, 1),
 (11556, 1),
 (11558, 1),
 (11574, 1),
 (11594, 1),
 (11595, 1),
 (11609, 1),
 (11610, 1),
 (11616, 1),
 (11622, 1),
 (11658, 1),
 (11667, 1),
 (11684, 1),
 (11688, 1),
 (11690, 1),
 (11716, 1),
 (11749, 1),
 (11752, 1),
 (11763, 1),
 (11765, 1),
 (11837, 1),
 (11861, 1),
 (11879, 1),
 (11892, 1),
 (11935, 1),
 (11979, 1),
 (11984, 1),
 (12005, 1),
 (12020, 1),
 (12023, 1),
 (12025, 1),
 (12040, 1),
 (12057, 1),
 (12103, 1),
 (12104, 1),
 (12125, 1),
 (12138, 1),
 (12148, 1),
 (12173, 1),
 (12204, 1),
 (12213, 1),
 (12222, 1),
 (12246, 1),
 (12248, 1),
 (12250, 1),
 (12256, 1),
 (12263, 1),
 (12279, 1),
 (12299, 1),
 (12319, 1),
 (12326, 1),
 (12365, 1),
 (12369, 1),
 (12382, 1),
 (12407, 1),
 (12409, 1),
 (12419, 1),
 (12428, 1),
 (12442, 1),
 (12457, 1),
 (12458, 1),
 (12462, 1),
 (12464, 1),
 (12491, 1),
 (12500, 1),
 (12508, 1),
 (12518, 1),
 (12551, 1),
 (12565, 1),
 (12578, 1),
 (12584, 1),
 (12604, 1),
 (12606, 1),
 (12636, 1),
 (12640, 1),
 (12645, 1),
 (12662, 1),
 (12664, 1),
 (12687, 1),
 (12688, 1),
 (12702, 1),
 (12704, 1),
 (12738, 1),
 (12754, 1),
 (12766, 1),
 (12781, 1),
 (14316, 1),
 (14321, 1),
 (14347, 1),
 (14364, 1),
 (14412, 1),
 (14416, 1),
 (14425, 1),
 (14460, 1),
 (14527, 1),
 (14535, 1),
 (14545, 1),
 (14566, 1),
 (14575, 1),
 (14590, 1),
 (14591, 1),
 (14632, 1),
 (14636, 1),
 (14637, 1),
 (14698, 1),
 (14699, 1),
 (14729, 1),
 (14783, 1),
 (14791, 1),
 (14803, 1),
 (14831, 1),
 (14851, 1),
 (14861, 1),
 (14871, 1),
 (14892, 1),
 (14909, 1),
 (15122, 1),
 (15135, 1),
 (15173, 1),
 (15193, 1),
 (15212, 1),
 (15240, 1),
 (15249, 1),
 (15277, 1),
 (15297, 1),
 (15306, 1),
 (15333, 1),
 (15353, 1),
 (15386, 1),
 (15407, 1),
 (15471, 1),
 (15516, 1),
 (15519, 1),
 (15529, 1),
 (15530, 1),
 (15548, 1),
 (15561, 1),
 (15583, 1),
 (15663, 1),
 (15678, 1),
 (15787, 1),
 (15802, 1),
 (15833, 1),
 (15853, 1),
 (15869, 1),
 (15873, 1),
 (15893, 1),
 (15923, 1),
 (15944, 1),
 (15981, 1),
 (15988, 1),
 (16010, 1),
 (16016, 1),
 (16027, 1),
 (16034, 1),
 (16045, 1),
 (16065, 1),
 (16101, 1),
 (16155, 1),
 (16170, 1),
 (16220, 1),
 (16236, 1),
 (16246, 1),
 (16305, 1),
 (16317, 1),
 (16321, 1),
 (16326, 1),
 (16328, 1),
 (16345, 1),
 (16402, 1),
 (16442, 1),
 (16473, 1),
 (16478, 1),
 (16567, 1),
 (16623, 1),
 (16644, 1),
 (16705, 1),
 (16718, 1),
 (16742, 1),
 (16771, 1),
 (16806, 1),
 (16812, 1),
 (16814, 1),
 (16852, 1),
 (16892, 1),
 (16936, 1),
 (16946, 1),
 (16949, 1),
 (16956, 1),
 (16968, 1),
 (16969, 1),
 (16989, 1),
 (17001, 1),
 (17033, 1),
 (17038, 1),
 (17041, 1),
 (17054, 1),
 (17079, 1),
 (17094, 1),
 (17097, 1),
 (17112, 1),
 (17119, 1),
 (17151, 1),
 (17191, 1),
 (17214, 1),
 (17239, 1),
 (17281, 1),
 (17301, 1),
 (17336, 1),
 (17352, 1),
 (17356, 1),
 (17406, 1),
 (17451, 1),
 (17503, 1),
 (17527, 1),
 (17539, 1),
 (17563, 1),
 (17607, 1),
 (17648, 1),
 (17659, 1),
 (17667, 1),
 (17683, 1),
 (17729, 1),
 (17772, 1),
 (17790, 1),
 (17805, 1),
 (17811, 1),
 (17843, 1),
 (17888, 1),
 (17905, 1),
 (17917, 1),
 (17922, 1),
 (17941, 1),
 (17967, 1),
 (17978, 1),
 (18055, 1),
 (18059, 1),
 (18074, 1),
 (18114, 1),
 (18131, 1),
 (18145, 1),
 (18198, 1),
 (18207, 1),
 (18240, 1),
 (18271, 1),
 (18282, 1),
 (18329, 1),
 (18352, 1),
 (18363, 1),
 (18394, 1),
 (18396, 1),
 (18465, 1),
 (18500, 1),
 (18529, 1),
 (18555, 1),
 (18563, 1),
 (18588, 1),
 (18608, 1),
 (18626, 1),
 (18640, 1),
 (18686, 1),
 (18703, 1),
 (18705, 1),
 (18707, 1),
 (18717, 1),
 (18722, 1),
 (18726, 1),
 (18744, 1),
 (18766, 1),
 (18946, 1),
 (18950, 1),
 (18951, 1),
 (18958, 1),
 (18974, 1),
 (18978, 1),
 (18980, 1),
 (19069, 1),
 (19102, 1),
 (19108, 1),
 (19312, 1),
 (19477, 1),
 (20115, 1),
 (20122, 1),
 (20125, 1),
 (20132, 1),
 (20146, 1),
 (20150, 1),
 (20158, 1),
 (20178, 1),
 (20200, 1),
 (20803, 1),
 (20817, 1),
 (20845, 1),
 (20969, 1),
 (20972, 1),
 (20988, 1),
 (20991, 1),
 (20996, 1),
 (21000, 1),
 (21002, 1),
 (21014, 1),
 (21032, 1),
 (21044, 1),
 (21075, 1),
 (21085, 1),
 (21111, 1),
 (21164, 1),
 (21254, 1),
 (21279, 1),
 (21290, 1),
 (21292, 1),
 (21303, 1),
 (21328, 1),
 (21336, 1),
 (21392, 1),
 (21393, 1),
 (21395, 1),
 (21993, 1),
 (21995, 1),
 (22001, 1),
 (22005, 1),
 (22024, 1),
 (22028, 1),
 (22067, 1),
 (22667, 1),
 (22681, 1),
 (22687, 1),
 (22694, 1),
 (22712, 1),
 (22816, 1),
 (22832, 1),
 (22837, 1),
 (22840, 1),
 (22855, 1),
 (22865, 1),
 (22870, 1),
 (22880, 1),
 (22881, 1),
 (22897, 1),
 (22903, 1),
 (22912, 1),
 (22917, 1),
 (22922, 1),
 (22925, 1),
 (22946, 1),
 (22994, 1),
 (22999, 1),
 (23009, 1),
 (23099, 1),
 (23229, 1),
 (23282, 1),
 (23473, 1),
 (23560, 1),
 (23842, 1),
 (24485, 1),
 (24615, 1),
 (24862, 1),
 (24866, 1),
 (24880, 1),
 (24883, 1),
 (24889, 1),
 (24899, 1),
 (24911, 1),
 (24941, 1),
 (24952, 1),
 (24954, 1),
 (24979, 1),
 (24984, 1),
 (25117, 1),
 (25119, 1),
 (25132, 1),
 (25185, 1),
 (25199, 1),
 (25205, 1),
 (25213, 1),
 (25267, 1),
 (26009, 1),
 (26010, 1),
 (26038, 1),
 (26106, 1),
 (26239, 1),
 (26244, 1),
 (26311, 1),
 (26323, 1),
 (26342, 1),
 (26343, 1),
 (26480, 1),
 (26618, 1),
 (27516, 1),
 (27549, 1),
 (27648, 1),
 (27690, 1),
 (27818, 1),
 (27847, 1),
 (27850, 1),
 (27926, 1),
 (28635, 1),
 (28659, 1),
 (28691, 1),
 (28979, 1),
 (29125, 1),
 (29131, 1),
 (29157, 1),
 (29194, 1),
 (29221, 1),
 (29453, 1),
 (30057, 1),
 (30102, 1),
 (30138, 1),
 (30192, 1),
 (30278, 1),
 (30316, 1),
 (30364, 1),
 (30481, 1),
 (30570, 1),
 (30655, 1),
 (31536, 1),
 (32173, 1),
 (32176, 1),
 (32192, 1),
 (32208, 1),
 (32244, 1),
 (32346, 1),
 (32347, 1),
 (32351, 1),
 (32382, 1),
 (32443, 1),
 (32476, 1),
 (33130, 1),
 (33207, 1),
 (33211, 1),
 (33213, 1),
 (33214, 1),
 (33229, 1),
 (33886, 1),
 (33904, 1),
 (33922, 1),
 (33925, 1),
 (33939, 1),
 (33964, 1),
 (33971, 1),
 (33980, 1),
 (33985, 1),
 (33988, 1),
 (33994, 1),
 (34608, 1),
 (34621, 1),
 (34631, 1),
 (34654, 1),
 (34662, 1),
 (34832, 1),
 (34843, 1),
 (34870, 1),
 (34875, 1),
 (34901, 1),
 (34974, 1),
 (34979, 1),
 (35141, 1),
 (35143, 1),
 (35145, 1),
 (35206, 1),
 (35815, 1),
 (35818, 1),
 (35830, 1),
 (35834, 1),
 (35912, 1),
 (36060, 1),
 (36077, 1),
 (36724, 1),
 (36740, 1),
 (36790, 1),
 (36802, 1),
 (36808, 1),
 (36816, 1),
 (36829, 1),
 (36877, 1),
 (36883, 1),
 (37786, 1),
 (37839, 1),
 (37885, 1),
 (37900, 1),
 (37993, 1),
 (38154, 1),
 (38209, 1),
 (38211, 1),
 (38320, 1),
 (38374, 1),
 (39084, 1),
 (39146, 1),
 (39819, 1),
 (39980, 1),
 (40025, 1),
 (40064, 1),
 (40077, 1),
 (40090, 1),
 (40092, 1),
 (40107, 1),
 (40111, 1),
 (40266, 1),
 (40295, 1),
 (40395, 1),
 (40491, 1),
 (40550, 1),
 (40681, 1),
 (40695, 1),
 (41462, 1),
 (41483, 1),
 (42809, 1),
 (42812, 1),
 (42846, 1),
 (43478, 1),
 (43507, 1),
 (43515, 1),
 (43524, 1),
 (43529, 1),
 (43700, 1),
 (43759, 1),
 (43774, 1),
 (43800, 1),
 (43801, 1),
 (43804, 1),
 (43842, 1),
 (43872, 1),
 (43918, 1),
 (43941, 1),
 (44182, 1),
 (44230, 1),
 (44457, 1),
 (44458, 1),
 (44476, 1),
 (44482, 1),
 (44520, 1),
 (44671, 1),
 (44681, 1),
 (44694, 1),
 (44814, 1),
 (44982, 1),
 (44999, 1),
 (45003, 1),
 (45179, 1),
 (45201, 1),
 (45209, 1),
 (45265, 1),
 (45885, 1),
 (45964, 1),
 (45984, 1),
 (45990, 1),
 (47364, 1),
 (47451, 1),
 (47465, 1),
 (47473, 1),
 (48328, 1),
 (48360, 1),
 (48376, 1),
 (48382, 1),
 (48390, 1),
 (48438, 1),
 (48485, 1),
 (48501, 1),
 (48533, 1),
 (49171, 1),
 (49783, 1),
 (49819, 1),
 (49824, 1),
 (49827, 1),
 (49829, 1),
 (49850, 1),
 (49905, 1),
 (49908, 1),
 (49928, 1),
 (50582, 1),
 (50614, 1),
 (50656, 1),
 (51342, 1),
 (51372, 1),
 (51387, 1),
 (51396, 1),
 (51461, 1),
 (51464, 1),
 (51512, 1),
 (51916, 1),
 (52145, 1),
 (52163, 1),
 (52274, 1),
 (52301, 1),
 (52509, 1),
 (52571, 1),
 (52585, 1),
 (52597, 1),
 (52621, 1),
 (52648, 1),
 (52705, 1),
 (52741, 1),
 (52755, 1),
 (52852, 1),
 (52891, 1),
 (52892, 1),
 (53192, 1),
 (53202, 1),
 (53277, 1),
 (53339, 1),
 (53424, 1),
 (53438, 1),
 (53855, 1),
 (53923, 1),
 (53925, 1),
 (53938, 1),
 (53943, 1),
 (53950, 1),
 (54017, 1),
 (54043, 1),
 (54046, 1),
 (54048, 1),
 (54062, 1),
 (54338, 1),
 (54356, 1),
 (54493, 1),
 (54562, 1),
 (54657, 1),
 (54680, 1),
 (55039, 1),
 (55112, 1),
 (55119, 1),
 (55123, 1),
 (55136, 1),
 (55178, 1),
 (55183, 1),
 (55199, 1),
 (55203, 1),
 (55205, 1),
 (55211, 1),
 (55353, 1),
 (55392, 1),
 (55396, 1),
 (55406, 1),
 (55433, 1),
 (55530, 1),
 (55538, 1),
 (55541, 1),
 (55691, 1),
 (55906, 1),
 (56166, 1),
 (56222, 1),
 (56315, 1),
 (56563, 1),
 (56645, 1),
 (56649, 1),
 (56662, 1),
 (56706, 1),
 (56711, 1),
 (56738, 1),
 (56747, 1),
 (56832, 1),
 (56845, 1),
 (56847, 1),
 (56863, 1),
 (56872, 1),
 (56911, 1),
 (56914, 1),
 (56959, 1),
 (56994, 1),
 (57024, 1),
 (57032, 1),
 (57044, 1),
 (57406, 1),
 (57411, 1),
 (57431, 1),
 (57462, 1),
 (57466, 1),
 (57475, 1),
 (57488, 1),
 (57532, 1),
 (57609, 1),
 (57611, 1),
 (57641, 1),
 (57645, 1),
 (57657, 1),
 (57666, 1),
 (57687, 1),
 (57708, 1),
 (57854, 1),
 (58048, 1),
 (58121, 1),
 (58146, 1),
 (58233, 1),
 (58295, 1),
 (58319, 1),
 (58341, 1),
 (58475, 1),
 (58736, 1),
 (58746, 1),
 (58754, 1),
 (58756, 1),
 (58760, 1),
 (58776, 1),
 (58889, 1),
 (59095, 1),
 (59114, 1),
 (59175, 1),
 (59227, 1),
 (59231, 1),
 (59343, 1),
 (59408, 1),
 (59517, 1),
 (59521, 1),
 (59527, 1),
 (59599, 1),
 (59604, 1),
 (59621, 1),
 (59655, 1),
 (59691, 1),
 (59693, 1),
 (59744, 1),
 (59756, 1),
 (59759, 1),
 (59777, 1),
 (59779, 1),
 (59945, 1),
 (59983, 1),
 (59996, 1),
 (60020, 1),
 (60059, 1),
 (60077, 1),
 (60091, 1),
 ...]

In [ ]:
%%sql
SELECT id, count(*)
FROM mdl_logstore_standard_log
WHERE action = 'viewed'
GROUP BY id

 * postgresql://postgres:***@localhost/moodle
120167 rows affected.

### Overall grade of learners

In [70]:
%%sql
SELECT userid,
ROUND(SUM(finalgrade)/COUNT(*)) AS overall_grade
FROM mdl_grade_grades
WHERE finalgrade IS NOT NULL
GROUP BY userid

 * postgresql://postgres:***@localhost/moodle
402 rows affected.

[(351, Decimal('70')),
 (87, Decimal('100')),
 (184, Decimal('100')),
 (116, Decimal('73')),
 (273, Decimal('100')),
 (394, Decimal('0')),
 (51, Decimal('49')),
 (272, Decimal('51')),
 (70, Decimal('100')),
 (190, Decimal('136')),
 (278, Decimal('71')),
 (176, Decimal('100')),
 (169, Decimal('100')),
 (299, Decimal('51')),
 (92, Decimal('100')),
 (541, Decimal('51')),
 (436, Decimal('2')),
 (180, Decimal('83')),
 (292, Decimal('100')),
 (236, Decimal('69')),
 (22, Decimal('100')),
 (271, Decimal('57')),
 (263, Decimal('73')),
 (156, Decimal('71')),
 (197, Decimal('100')),
 (135, Decimal('52')),
 (470, Decimal('100')),
 (759, Decimal('75')),
 (879, Decimal('97')),
 (227, Decimal('100')),
 (775, Decimal('195')),
 (282, Decimal('47')),
 (390, Decimal('92')),
 (173, Decimal('100')),
 (149, Decimal('46')),
 (269, Decimal('100')),
 (73, Decimal('76')),
 (261, Decimal('100')),
 (103, Decimal('65')),
 (502, Decimal('2')),
 (280, Decimal('82')),
 (42, Decimal('168')),
 (189, Decimal('75')),
 (117, Decimal('100')),
 (239, Decimal('100')),
 (161, Decimal('48')),
 (121, Decimal('44')),
 (88, Decimal('136')),
 (420, Decimal('58')),
 (188, Decimal('52')),
 (113, Decimal('100')),
 (125, Decimal('100')),
 (257, Decimal('100')),
 (40, Decimal('73')),
 (240, Decimal('100')),
 (328, Decimal('160')),
 (43, Decimal('48')),
 (196, Decimal('100')),
 (120, Decimal('72')),
 (291, Decimal('72')),
 (15, Decimal('100')),
 (440, Decimal('103')),
 (226, Decimal('100')),
 (210, Decimal('62')),
 (843, Decimal('44')),
 (48, Decimal('65')),
 (349, Decimal('49')),
 (187, Decimal('100')),
 (914, Decimal('53')),
 (842, Decimal('197')),
 (298, Decimal('100')),
 (57, Decimal('73')),
 (81, Decimal('100')),
 (19, Decimal('100')),
 (61, Decimal('42')),
 (244, Decimal('100')),
 (160, Decimal('52')),
 (721, Decimal('100')),
 (242, Decimal('64')),
 (331, Decimal('51')),
 (251, Decimal('100')),
 (204, Decimal('100')),
 (104, Decimal('100')),
 (266, Decimal('168')),
 (5, Decimal('57')),
 (171, Decimal('100')),
 (307, Decimal('2')),
 (397, Decimal('0')),
 (91, Decimal('100')),
 (427, Decimal('163')),
 (786, Decimal('56')),
 (283, Decimal('100')),
 (347, Decimal('158')),
 (29, Decimal('100')),
 (179, Decimal('42')),
 (54, Decimal('55')),
 (686, Decimal('60')),
 (297, Decimal('100')),
 (181, Decimal('100')),
 (361, Decimal('66')),
 (96, Decimal('100')),
 (201, Decimal('168')),
 (303, Decimal('7')),
 (844, Decimal('10')),
 (105, Decimal('44')),
 (107, Decimal('72')),
 (233, Decimal('72')),
 (866, Decimal('141')),
 (220, Decimal('100')),
 (86, Decimal('47')),
 (400, Decimal('9')),
 (991, Decimal('100')),
 (93, Decimal('100')),
 (89, Decimal('100')),
 (373, Decimal('8')),
 (219, Decimal('100')),
 (1025, Decimal('245')),
 (175, Decimal('100')),
 (252, Decimal('100')),
 (241, Decimal('41')),
 (31, Decimal('100')),
 (363, Decimal('180')),
 (723, Decimal('55')),
 (285, Decimal('100')),
 (50, Decimal('83')),
 (253, Decimal('100')),
 (581, Decimal('126')),
 (14, Decimal('100')),
 (66, Decimal('100')),
 (231, Decimal('100')),
 (340, Decimal('166')),
 (109, Decimal('100')),
 (356, Decimal('100')),
 (13, Decimal('100')),
 (155, Decimal('100')),
 (133, Decimal('61')),
 (195, Decimal('100')),
 (199, Decimal('51')),
 (372, Decimal('62')),
 (75, Decimal('100')),
 (246, Decimal('168')),
 (369, Decimal('123')),
 (128, Decimal('100')),
 (714, Decimal('55')),
 (339, Decimal('10')),
 (243, Decimal('100')),
 (166, Decimal('100')),
 (344, Decimal('144')),
 (142, Decimal('100')),
 (924, Decimal('166')),
 (410, Decimal('184')),
 (534, Decimal('0')),
 (152, Decimal('100')),
 (428, Decimal('49')),
 (591, Decimal('54')),
 (383, Decimal('128')),
 (230, Decimal('100')),
 (747, Decimal('7')),
 (7, Decimal('100')),
 (301, Decimal('63')),
 (222, Decimal('70')),
 (381, Decimal('110')),
 (38, Decimal('56')),
 (757, Decimal('47')),
 (359, Decimal('100')),
 (193, Decimal('100')),
 (777, Decimal('28')),
 (164, Decimal('100')),
 (254, Decimal('71')),
 (377, Decimal('149')),
 (78, Decimal('51')),
 (453, Decimal('72')),
 (922, Decimal('100')),
 (159, Decimal('73')),
 (217, Decimal('175')),
 (186, Decimal('100')),
 (250, Decimal('64')),
 (47, Decimal('100')),
 (177, Decimal('100')),
 (20, Decimal('53')),
 (865, Decimal('196')),
 (750, Decimal('6')),
 (319, Decimal('0')),
 (182, Decimal('51')),
 (517, Decimal('9')),
 (106, Decimal('100')),
 (18, Decimal('100')),
 (110, Decimal('100')),
 (178, Decimal('100')),
 (145, Decimal('71')),
 (129, Decimal('100')),
 (27, Decimal('100')),
 (143, Decimal('72')),
 (203, Decimal('56')),
 (58, Decimal('69')),
 (228, Decimal('156')),
 (789, Decimal('100')),
 (346, Decimal('45')),
 (294, Decimal('112')),
 (71, Decimal('72')),
 (267, Decimal('100')),
 (229, Decimal('100')),
 (68, Decimal('100')),
 (80, Decimal('70')),
 (146, Decimal('44')),
 (52, Decimal('53')),
 (930, Decimal('245')),
 (607, Decimal('150')),
 (382, Decimal('171')),
 (162, Decimal('100')),
 (258, Decimal('73')),
 (341, Decimal('185')),
 (378, Decimal('49')),
 (132, Decimal('69')),
 (738, Decimal('100')),
 (84, Decimal('72')),
 (170, Decimal('159')),
 (192, Decimal('100')),
 (276, Decimal('100')),
 (101, Decimal('100')),
 (237, Decimal('54')),
 (69, Decimal('55')),
 (262, Decimal('67')),
 (348, Decimal('49')),
 (375, Decimal('52')),
 (114, Decimal('100')),
 (115, Decimal('72')),
 (60, Decimal('68')),
 (97, Decimal('100')),
 (238, Decimal('100')),
 (112, Decimal('100')),
 (108, Decimal('51')),
 (729, Decimal('100')),
 (59, Decimal('100')),
 (268, Decimal('74')),
 (289, Decimal('73')),
 (737, Decimal('100')),
 (65, Decimal('34')),
 (127, Decimal('100')),
 (124, Decimal('100')),
 (615, Decimal('104')),
 (98, Decimal('75')),
 (567, Decimal('66')),
 (200, Decimal('100')),
 (44, Decimal('64')),
 (235, Decimal('72')),
 (82, Decimal('100')),
 (119, Decimal('100')),
 (306, Decimal('8')),
 (286, Decimal('68')),
 (376, Decimal('48')),
 (153, Decimal('56')),
 (279, Decimal('100')),
 (147, Decimal('115')),
 (480, Decimal('194')),
 (214, Decimal('100')),
 (202, Decimal('100')),
 (9, Decimal('71')),
 (79, Decimal('100')),
 (989, Decimal('195')),
 (26, Decimal('100')),
 (85, Decimal('100')),
 (72, Decimal('100')),
 (945, Decimal('55')),
 (281, Decimal('100')),
 (95, Decimal('167')),
 (1041, Decimal('51')),
 (232, Decimal('100')),
 (77, Decimal('100')),
 (259, Decimal('164')),
 (302, Decimal('100')),
 (172, Decimal('100')),
 (409, Decimal('52')),
 (30, Decimal('100')),
 (288, Decimal('100')),
 (21, Decimal('100')),
 (131, Decimal('54')),
 (3, Decimal('100')),
 (17, Decimal('100')),
 (198, Decimal('75')),
 (28, Decimal('100')),
 (37, Decimal('100')),
 (212, Decimal('100')),
 (1027, Decimal('184')),
 (917, Decimal('67')),
 (249, Decimal('100')),
 (353, Decimal('56')),
 (489, Decimal('51')),
 (255, Decimal('72')),
 (165, Decimal('125')),
 (813, Decimal('55')),
 (56, Decimal('72')),
 (151, Decimal('53')),
 (209, Decimal('74')),
 (296, Decimal('71')),
 (74, Decimal('100')),
 (138, Decimal('47')),
 (225, Decimal('47')),
 (245, Decimal('100')),
 (205, Decimal('100')),
 (83, Decimal('100')),
 (67, Decimal('45')),
 (63, Decimal('100')),
 (90, Decimal('154')),
 (216, Decimal('100')),
 (174, Decimal('43')),
 (45, Decimal('167')),
 (443, Decimal('100')),
 (387, Decimal('195')),
 (295, Decimal('100')),
 (484, Decimal('100')),
 (213, Decimal('80')),
 (134, Decimal('72')),
 (274, Decimal('64')),
 (144, Decimal('100')),
 (39, Decimal('48')),
 (801, Decimal('89')),
 (918, Decimal('10')),
 (163, Decimal('100')),
 (168, Decimal('86')),
 (223, Decimal('84')),
 (36, Decimal('100')),
 (287, Decimal('100')),
 (362, Decimal('103')),
 (221, Decimal('100')),
 (752, Decimal('100')),
 (102, Decimal('208')),
 (167, Decimal('130')),
 (158, Decimal('72')),
 (277, Decimal('72')),
 (594, Decimal('62')),
 (290, Decimal('165')),
 (683, Decimal('100')),
 (300, Decimal('100')),
 (118, Decimal('80')),
 (265, Decimal('100')),
 (284, Decimal('155')),
 (111, Decimal('100')),
 (16, Decimal('44')),
 (207, Decimal('100')),
 (62, Decimal('100')),
 (123, Decimal('79')),
 (126, Decimal('79')),
 (194, Decimal('71')),
 (385, Decimal('136')),
 (99, Decimal('64')),
 (367, Decimal('100')),
 (374, Decimal('48')),
 (1019, Decimal('100')),
 (41, Decimal('100')),
 (46, Decimal('100')),
 (206, Decimal('100')),
 (224, Decimal('100')),
 (586, Decimal('166')),
 (157, Decimal('100')),
 (32, Decimal('100')),
 (53, Decimal('100')),
 (275, Decimal('100')),
 (247, Decimal('100')),
 (260, Decimal('72')),
 (618, Decimal('0')),
 (100, Decimal('100')),
 (183, Decimal('100')),
 (136, Decimal('100')),
 (150, Decimal('100')),
 (354, Decimal('48')),
 (139, Decimal('50')),
 (140, Decimal('54')),
 (593, Decimal('7')),
 (12, Decimal('100')),
 (248, Decimal('100')),
 (137, Decimal('105')),
 (208, Decimal('100')),
 (293, Decimal('100')),
 (411, Decimal('47')),
 (392, Decimal('100')),
 (24, Decimal('100')),
 (191, Decimal('100')),
 (25, Decimal('37')),
 (122, Decimal('100')),
 (94, Decimal('100')),
 (141, Decimal('51')),
 (218, Decimal('100')),
 (154, Decimal('100')),
 (434, Decimal('48')),
 (49, Decimal('100')),
 (234, Decimal('72')),
 (211, Decimal('100')),
 (256, Decimal('56')),
 (449, Decimal('152')),
 (64, Decimal('100')),
 (264, Decimal('100')),
 (185, Decimal('90')),
 (215, Decimal('100')),
 (742, Decimal('83')),
 (55, Decimal('56')),
 (148, Decimal('55')),
 (130, Decimal('67')),
 (23, Decimal('100')),
 (270, Decimal('56')),
 (846, Decimal('195')),
 (486, Decimal('58'))]

### Number of forum_posts

In [32]:
%%sql
SELECT COUNT(*)
FROM mdl_forum_posts ;

 * postgresql://postgres:***@localhost/moodle
1 rows affected.

[(131,)]